### PR TITLE
Clear color in display

### PR DESCRIPTION
**Pull request by jeremyfix**
Makes the display nicer.  Avoids to wonder why only a part of the viewport is displayed black.

### CODE REVIEW

**Comment by rougier** [comment]
Thanks. It was not cleared on purpose (it's written in the text just before the code) to exlain that you have to take care of everything.

**Comment by encukou** [comment]
On some systems (like most Linux & Windows), you'll get black even if you don't clear the screen explicitly.
To these readers, the note about "garbage" on the screen won't make sense.

**Comment by rougier** [comment]
@encukou Didn't know that.
@jeremyfix what is your system ?

**Comment by jeremyfix** [comment]
My display is not fully black. The display is initially 300 x 300 then reshaped in the code to 512x512. The 300x300 has some content , the remaining 212 pixel wide border is an instantaneous copy of my background. See below 




Some elements on my system (let me know if you need more) :
Ubuntu 18.04 , 64 bits
python 3.6.7
python-OpenGL  3.1.0

NVIDIA Corporation GF108GL [Quadro 600]
Kernel driver in use: nouveau
Kernel modules: nvidiafb, nouveau

**Comment by rougier** [comment]
Okay. Could you correct the text as well (where it is said there's garbage on the screen) then I'll merge your patch.

**Pull request merged**
